import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import "./globals.css";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <Provider>
            {/* paddingBottom prevents content from hiding behind fixed navbar */}
            <div style={{ minHeight: "100vh", paddingBottom: "120px" }}>
              {children}
              <Navbar />
            </div>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
